"""add options table

Revision ID: 023d09684845
Revises: 742e2bf030f2
Create Date: 2026-02-28 20:30:11.516909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023d09684845'
down_revision = '742e2bf030f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['question_id', 'position'])
        batch_op.drop_constraint(batch_op.f('options_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('options_question_id_fkey'), 'questions', ['question_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
