"""add sequence to questions

Revision ID: 742e2bf030f2
Revises: 404171516631
Create Date: 2026-02-28 20:08:06.115432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742e2bf030f2'
down_revision = '404171516631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
